'use client';
import { useState, useEffect } from 'react';
import { getStudentProfiles, recordPayment, addAuditLog, getSchoolProfile } from '@/lib/store';
import { StudentProfile, TermPayment } from '@/lib/types';
import { useAuth } from '@/hooks/use-auth';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Search, Wallet, Landmark } from 'lucide-react';
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { Badge } from '../ui/badge';
import { Label } from '../ui/label';
import { format } from 'date-fns';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import jsPDF from 'jspdf';
import 'jspdf-autotable';


const formatCurrency = (amount: number) => new Intl.NumberFormat('en-GH', { style: 'currency', currency: 'GHS' }).format(amount);

const generateReceipt = (student: StudentProfile, payment: {amount: number, method: string, receipt_number?: string, paid_by?: string}) => {
    const doc = new jsPDF();
    const schoolProfile = getSchoolProfile();
    const schoolName = schoolProfile?.schoolName || "CampusConnect School";
    const schoolContact = schoolProfile?.phone || "N/A";
    const receiptNumber = payment.receipt_number || `RCPT${Date.now()}`;
    
    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(schoolName, 105, 20, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Contact: ${schoolContact}`, 105, 27, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Official Payment Receipt", 105, 40, { align: 'center' });

    // Receipt Info
    doc.setFontSize(10);
    doc.text(`Receipt No: ${receiptNumber}`, 15, 55);
    doc.text(`Date: ${format(new Date(), 'PPP')}`, 170, 55, { align: 'right' });

    // Student Info
    (doc as any).autoTable({
        startY: 65,
        head: [['Student Name', 'Student ID', 'Class']],
        body: [[
            `${student.student.first_name} ${student.student.last_name}`,
            student.student.student_no,
            student.admissionDetails.class_assigned // You might want to map this to class name
        ]],
        theme: 'striped'
    });

    // Payment Details
    (doc as any).autoTable({
        startY: (doc as any).lastAutoTable.finalY + 10,
        head: [['Description', 'Amount']],
        body: [
            ['Amount Paid', formatCurrency(payment.amount)],
            ['Paid By', payment.paid_by || 'N/A'],
            ['Payment Method', payment.method],
        ],
        theme: 'striped',
        didDrawCell: (data: any) => {
            if (data.section === 'body' && data.column.index === 1) {
                if (data.row.index === 0) { // Amount Paid row
                    doc.setFont('helvetica', 'bold');
                }
            }
        }
    });

    // Total and Balance
    const latestTermPayment = student.financialDetails?.payment_history.slice(-1)[0];
    (doc as any).autoTable({
        startY: (doc as any).lastAutoTable.finalY + 5,
        body: [
            ['Previous Balance', formatCurrency((student.financialDetails?.account_balance || 0) + payment.amount)],
            ['Amount Paid', formatCurrency(payment.amount)],
            ['New Outstanding Balance', formatCurrency(student.financialDetails?.account_balance || 0)]
        ],
        theme: 'plain',
        styles: {
            cellPadding: 2,
            fontSize: 11
        },
        columnStyles: {
            0: { halign: 'right', fontStyle: 'bold' },
            1: { halign: 'right' }
        }
    });


    // Footer
    const finalY = (doc as any).lastAutoTable.finalY;
    doc.setFontSize(8);
    doc.text("Thank you for your payment.", 105, finalY + 20, { align: 'center' });
    doc.text("Generated by CampusConnect", 105, finalY + 25, { align: 'center' });

    // Download PDF
    doc.save(`Receipt_${receiptNumber}_${student.student.last_name}.pdf`);
};

export function FeeCollection() {
    const [searchQuery, setSearchQuery] = useState('');
    const [searchResults, setSearchResults] = useState<StudentProfile[]>([]);
    const [selectedStudent, setSelectedStudent] = useState<StudentProfile | null>(null);
    const [isPaymentDialogOpen, setIsPaymentDialogOpen] = useState(false);
    
    // Payment form state
    const [paymentAmount, setPaymentAmount] = useState<number | ''>('');
    const [paymentMethod, setPaymentMethod] = useState<'Cash' | 'Bank Transfer' | 'Mobile Money' | 'Card'>('Cash');
    const [receiptNumber, setReceiptNumber] = useState('');
    const [paidBy, setPaidBy] = useState('');

    const { user } = useAuth();
    const { toast } = useToast();

    useEffect(() => {
        if (searchQuery.length > 2) {
            const profiles = getStudentProfiles();
            const filtered = profiles.filter(p =>
                p.student.first_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                p.student.last_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                p.student.student_no.includes(searchQuery)
            );
            setSearchResults(filtered);
        } else {
            setSearchResults([]);
        }
    }, [searchQuery]);

    const handleSelectStudent = (student: StudentProfile) => {
        setSelectedStudent(student);
        setSearchQuery('');
        setSearchResults([]);
    };

    const handleRecordPayment = () => {
        if (!selectedStudent || !user || !paymentAmount) {
            toast({ variant: 'destructive', title: 'Error', description: 'Missing required payment details.' });
            return;
        }

        const paymentDetails = {
            amount: paymentAmount,
            method: paymentMethod,
            receipt_number: paymentMethod === 'Cash' ? receiptNumber : undefined,
            paid_by: paymentMethod === 'Cash' ? paidBy : undefined,
        };

        const updatedProfile = recordPayment(selectedStudent.student.student_no, paymentDetails, user.id);
        
        if (updatedProfile) {
            setSelectedStudent(updatedProfile);
            toast({ title: 'Payment Recorded', description: `Payment of ${formatCurrency(paymentAmount)} recorded for ${updatedProfile.student.first_name}.` });
            addAuditLog({
                user: user.email,
                name: user.name,
                action: 'Record Payment',
                details: `Recorded payment of ${formatCurrency(paymentAmount)} for student ${updatedProfile.student.student_no}`
            });
            
            generateReceipt(updatedProfile, paymentDetails);

            setIsPaymentDialogOpen(false);
            setPaymentAmount('');
            setReceiptNumber('');
            setPaidBy('');
        } else {
            toast({ variant: 'destructive', title: 'Error', description: 'Failed to record payment.' });
        }
    };

    const latestTermPayment = selectedStudent?.financialDetails?.payment_history
        .sort((a, b) => new Date(b.payment_date || 0).getTime() - new Date(a.payment_date || 0).getTime())[0];

    return (
        <div className="grid md:grid-cols-3 gap-6">
            <div className="md:col-span-1">
                <Card>
                    <CardHeader>
                        <CardTitle>Find Student</CardTitle>
                        <CardDescription>Search by name or student ID.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className="relative">
                            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                            <Input
                                placeholder="Start typing to search..."
                                className="pl-8"
                                value={searchQuery}
                                onChange={(e) => setSearchQuery(e.target.value)}
                            />
                        </div>
                        <div className="mt-4 space-y-2">
                            {searchResults.map(student => (
                                <Button
                                    key={student.student.student_no}
                                    variant="ghost"
                                    className="w-full justify-start h-auto"
                                    onClick={() => handleSelectStudent(student)}
                                >
                                    <Avatar className="h-9 w-9 mr-3">
                                        <AvatarImage src={student.student.avatarUrl} />
                                        <AvatarFallback>{student.student.first_name[0]}{student.student.last_name[0]}</AvatarFallback>
                                    </Avatar>
                                    <div>
                                        <p className="font-semibold text-left">{student.student.first_name} {student.student.last_name}</p>
                                        <p className="text-sm text-muted-foreground text-left">{student.student.student_no}</p>
                                    </div>
                                </Button>
                            ))}
                        </div>
                    </CardContent>
                </Card>
            </div>
            <div className="md:col-span-2">
                {selectedStudent ? (
                    <div className="space-y-6">
                        <Card>
                            <CardHeader>
                                <div className="flex items-center justify-between">
                                    <div className="flex items-center gap-4">
                                        <Avatar className="h-16 w-16">
                                            <AvatarImage src={selectedStudent.student.avatarUrl} />
                                            <AvatarFallback className="text-2xl">{selectedStudent.student.first_name[0]}{selectedStudent.student.last_name[0]}</AvatarFallback>
                                        </Avatar>
                                        <div>
                                            <CardTitle>{selectedStudent.student.first_name} {selectedStudent.student.last_name}</CardTitle>
                                            <CardDescription>{selectedStudent.student.student_no}</CardDescription>
                                        </div>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-sm text-muted-foreground">Total Outstanding</p>
                                        <p className="text-2xl font-bold text-red-600">{formatCurrency(selectedStudent.financialDetails?.account_balance ? Math.abs(selectedStudent.financialDetails.account_balance) : 0)}</p>
                                    </div>
                                </div>
                            </CardHeader>
                            <CardContent>
                                <div className="border-t pt-4">
                                    <h4 className="font-semibold mb-2">Current Term Bill ({latestTermPayment?.term})</h4>
                                    <div className="space-y-1 text-sm">
                                        {latestTermPayment?.bill_items.map((item, index) => (
                                            <div key={index} className="flex justify-between">
                                                <p className="text-muted-foreground">{item.description}</p>
                                                <p>{formatCurrency(item.amount)}</p>
                                            </div>
                                        ))}
                                        <div className="flex justify-between font-bold border-t pt-2 mt-2">
                                            <p>Total Billed</p>
                                            <p>{formatCurrency(latestTermPayment?.total_fees || 0)}</p>
                                        </div>
                                        <div className="flex justify-between font-medium text-green-600">
                                            <p>Amount Paid</p>
                                            <p>{formatCurrency(latestTermPayment?.amount_paid || 0)}</p>
                                        </div>
                                    </div>
                                </div>
                            </CardContent>
                            <CardFooter className="justify-end">
                                <Dialog open={isPaymentDialogOpen} onOpenChange={setIsPaymentDialogOpen}>
                                    <DialogTrigger asChild>
                                        <Button><Wallet className="mr-2 h-4 w-4" /> Record Payment</Button>
                                    </DialogTrigger>
                                    <DialogContent>
                                        <DialogHeader>
                                            <DialogTitle>Record Payment for {selectedStudent.student.first_name}</DialogTitle>
                                            <DialogDescription>
                                                Enter the amount being paid. The current outstanding balance is <span className="font-bold">{formatCurrency(selectedStudent.financialDetails?.account_balance ? Math.abs(selectedStudent.financialDetails.account_balance) : 0)}</span>.
                                            </DialogDescription>
                                        </DialogHeader>
                                        <div className="space-y-4 py-4">
                                            <div className="space-y-2">
                                                <Label htmlFor="amount">Amount (GHS)</Label>
                                                <Input id="amount" type="number" value={paymentAmount} onChange={(e) => setPaymentAmount(Number(e.target.value))} placeholder="0.00" />
                                            </div>
                                            <div className="space-y-2">
                                                <Label htmlFor="method">Payment Method</Label>
                                                <Select value={paymentMethod} onValueChange={(value) => setPaymentMethod(value as any)}>
                                                    <SelectTrigger><SelectValue /></SelectTrigger>
                                                    <SelectContent>
                                                        <SelectItem value="Cash">Cash</SelectItem>
                                                        <SelectItem value="Bank Transfer">Bank Transfer</SelectItem>
                                                        <SelectItem value="Mobile Money">Mobile Money</SelectItem>
                                                        <SelectItem value="Card">Card</SelectItem>
                                                    </SelectContent>
                                                </Select>
                                            </div>
                                            {paymentMethod === 'Cash' && (
                                                <>
                                                    <div className="space-y-2">
                                                        <Label htmlFor="paid_by">Paid By</Label>
                                                        <Input id="paid_by" value={paidBy} onChange={(e) => setPaidBy(e.target.value)} placeholder="e.g., John Doe (Father)" />
                                                    </div>
                                                    <div className="space-y-2">
                                                        <Label htmlFor="receipt_number">Receipt Number</Label>
                                                        <Input id="receipt_number" value={receiptNumber} onChange={(e) => setReceiptNumber(e.target.value)} placeholder="Enter manual receipt number" />
                                                    </div>
                                                </>
                                            )}
                                        </div>
                                        <DialogFooter>
                                            <Button variant="outline" onClick={() => setIsPaymentDialogOpen(false)}>Cancel</Button>
                                            <Button onClick={handleRecordPayment}>Confirm Payment & Generate Receipt</Button>
                                        </DialogFooter>
                                    </DialogContent>
                                </Dialog>
                            </CardFooter>
                        </Card>
                        <Card>
                            <CardHeader>
                                <div className="flex items-center gap-4">
                                    <Landmark className="h-6 w-6 text-primary"/>
                                    <div>
                                        <CardTitle>Payment History</CardTitle>
                                        <CardDescription>Full payment history for {selectedStudent.student.first_name}.</CardDescription>
                                    </div>
                                </div>
                            </CardHeader>
                            <CardContent>
                                {selectedStudent.financialDetails && selectedStudent.financialDetails.payment_history.length > 0 ? (
                                    <div className="rounded-md border">
                                        <Table>
                                            <TableHeader>
                                                <TableRow>
                                                    <TableHead>Term</TableHead>
                                                    <TableHead>Total Billed</TableHead>
                                                    <TableHead>Amount Paid</TableHead>
                                                    <TableHead>Outstanding</TableHead>
                                                    <TableHead>Status</TableHead>
                                                </TableRow>
                                            </TableHeader>
                                            <TableBody>
                                                {selectedStudent.financialDetails.payment_history.map((rec, i) => (
                                                    <TableRow key={i}>
                                                        <TableCell className="font-medium">{rec.term}</TableCell>
                                                        <TableCell>{formatCurrency(rec.total_fees)}</TableCell>
                                                        <TableCell className="text-green-600">{formatCurrency(rec.amount_paid)}</TableCell>
                                                        <TableCell className="text-red-600">{formatCurrency(rec.outstanding)}</TableCell>
                                                        <TableCell>
                                                            <Badge variant={rec.status === 'Paid' ? 'secondary' : (rec.status === 'Partially Paid' ? 'default' : 'destructive')}>
                                                                {rec.status}
                                                            </Badge>
                                                        </TableCell>
                                                    </TableRow>
                                                ))}
                                            </TableBody>
                                        </Table>
                                    </div>
                                ) : (
                                    <p className="text-muted-foreground text-center py-8">No payment history found.</p>
                                )}
                            </CardContent>
                        </Card>
                    </div>
                ) : (
                    <div className="flex items-center justify-center h-full rounded-lg border-2 border-dashed border-muted-foreground/30 text-muted-foreground p-12">
                        <p>Select a student to view their financial details.</p>
                    </div>
                )}
            </div>
        </div>
    );
}
